2022-07-22 01:36:48,718 - WARNING - _internal -  * Debugger is active!
2022-07-22 01:38:12,131 - WARNING - _internal -  * Debugger is active!
2022-07-22 01:45:53,379 - WARNING - _internal -  * Debugger is active!
2022-07-22 01:45:58,832 - ERROR - utils_classes - Error on 2022-07-21T23:45:58.821472 
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 432, in katapi
    ErrorLog.dump_error(timestamp)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 614, in dump_error
    traceback.print_stack(file=dummy1)
Traceback (most recent call last):
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 425, in katapi
    response = XmlTei.build_response(req, response_body, timestamp, status_code)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 288, in build_response
    tei_body.append(response_body)
TypeError: Argument 'element' has incorrect type (expected lxml.etree._Element, got _io.TextIOWrapper)

2022-07-22 01:58:35,760 - WARNING - _internal -  * Debugger is active!
2022-07-22 01:58:41,909 - ERROR - utils_classes - Error on 2022-07-21T23:58:41.892884 
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 436, in katapi
    ErrorLog.dump_error(timestamp)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 625, in dump_error
    traceback.print_stack(file=dummy1)
Traceback (most recent call last):
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 429, in katapi
    response = XmlTei.build_response(req, response_body, timestamp, status_code)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 305, in build_response
    tree, xml_declaration=True, encoding="utf-8"
UnboundLocalError: local variable 'tree' referenced before assignment

2022-07-22 02:00:15,840 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:00:21,298 - ERROR - utils_classes - Error on 2022-07-22T00:00:21.292934 
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 436, in katapi
    ErrorLog.dump_error(timestamp)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 626, in dump_error
    traceback.print_stack(file=dummy1)
Traceback (most recent call last):
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 429, in katapi
    response = XmlTei.build_response(req, response_body, timestamp, status_code)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 306, in build_response
    tree, xml_declaration=True, encoding="utf-8"
UnboundLocalError: local variable 'tree' referenced before assignment

2022-07-22 02:00:38,281 - ERROR - utils_classes - Error on 2022-07-22T00:00:38.279153 
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 436, in katapi
    ErrorLog.dump_error(timestamp)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 626, in dump_error
    # prepare the error stack
Traceback (most recent call last):
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 429, in katapi
    response = XmlTei.build_response(req, response_body, timestamp, status_code)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 306, in build_response
    # to check the output quality: save tei output to file
UnboundLocalError: local variable 'tree' referenced before assignment

2022-07-22 02:00:43,883 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:00:56,654 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:01:01,993 - ERROR - utils_classes - Error on 2022-07-22T00:01:01.989026 
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 436, in katapi
    ErrorLog.dump_error(timestamp)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 629, in dump_error
    traceback.print_stack(file=dummy1)
Traceback (most recent call last):
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 429, in katapi
    response = XmlTei.build_response(req, response_body, timestamp, status_code)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 309, in build_response
    tree, xml_declaration=True, encoding="utf-8"
UnboundLocalError: local variable 'tree' referenced before assignment

2022-07-22 02:02:30,217 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:02:38,831 - ERROR - utils_classes - Error on 2022-07-22T00:02:38.826755 
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/env_app/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 436, in katapi
    ErrorLog.dump_error(timestamp)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 626, in dump_error
    traceback.print_stack(file=dummy1)
Traceback (most recent call last):
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/routes/routes_api.py", line 429, in katapi
    response = XmlTei.build_response(req, response_body, timestamp, status_code)
  File "/home/paulhector/documents/enc_tnah/mss/travail/Application/APP/utils/utils_classes.py", line 306, in build_response
    tree, xml_declaration=True, encoding="utf-8"
UnboundLocalError: local variable 'tree' referenced before assignment

2022-07-22 02:03:24,328 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:06:27,026 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:07:02,746 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:14:53,589 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:30:43,868 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:34:08,862 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:34:38,051 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:35:09,102 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:35:16,561 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:36:11,958 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:37:01,532 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:38:36,647 - WARNING - _internal -  * Debugger is active!
2022-07-22 02:38:45,491 - WARNING - _internal -  * Debugger is active!
